### ISSUE TITLE
how to add min and max datetime for angular-schema-form-datetime-edit?

### ISSUE THREAD

**Issue by kirantej1225** [andrglo/angular-schema-form-datetime-edit#1]
hi

could you please provide me a solution on how to add min and max datetime for angular-schema-form-datetime-edit?

my requirement 
1.set min and max datetime
2.what ever I set min and max datetime should be populated without any error at the time of loading

**Comment by andrglo** [comment]
Sorry, I do not use nor maintain this repo since 2015
